### ISSUE TITLE
Pagina de bienvenida del sitio

### ISSUE THREAD

**Issue by GastonZ** [GastonZ/SaborLatinoBrewingCo#1]
Como usuario quiero ver la pagina de bienvenida 
Quiero poder poner mi fecha de nacimiento en ella para saber si puedo ingresar
Para saber si soy lo suficientemente  mayor con tal de ingresar

Requirimientos extras : El fondo va a ser una imagen bien fachera ,  el input donde el usuario tiene que escribir debe tener un diseño acorde a la pagina de cervezas , debe funcionar en responsive .

**Comment by BelenPe1999** [comment]
terminado
